autofill: []
sort:
  - access
  - line
descriptionPath: README.md
groups:
  api: API Docs
  undefined: Other
basePath: https://github.com/lolmaus/breakpoint-slicer/tree/gen-3
package:
  name: breakpoint-slicer
  title: Breakpoint Slicer
  description: Slice media queries with ease
  homepage: https://github.com/lolmaus/breakpoint-slicer
  license: MIT
